### ISSUE TITLE
Error with yolov4-tiny inference

### ISSUE THREAD

**Issue by 4444borja** [TNTWEN/OpenVINO-YOLOV4#14]
Hi! I have tried converting yolov4.weights (full model) and running an inference, everything works fine.
However, when I do the same thing but with yolov4-tiny.weights (tiny version) everything is okay until object_detection_demo_yolov3_async.py starts the inference. Then this error occurs:

```
[ INFO ] Creating Inference Engine...
[ INFO ] Loading network
[ INFO ] Preparing inputs
[ WARN:0] global ../opencv/modules/videoio/src/cap_gstreamer.cpp (898) open OpenCV | GStreamer warning: unable to query duration of stream
[ WARN:0] global ../opencv/modules/videoio/src/cap_gstreamer.cpp (935) open OpenCV | GStreamer warning: Cannot query video position: status=1, value=0, duration=-1
[ INFO ] Loading model to the plugin
[ INFO ] Starting inference...

Traceback (most recent call last):
  File "object_detection_demo_yolov3_async.py", line 518, in <module>
    sys.exit(main() or 0)
  File "object_detection_demo_yolov3_async.py", line 398, in main
    args.keep_aspect_ratio)
  File "object_detection_demo_yolov3_async.py", line 233, in get_objects
    out_blob = out_blob.buffer.reshape(net.layers[net.layers[layer_name].parents[0]].out_data[0].shape)
KeyError: 'detector/yolo-v4-tiny/strided_slice/Split.0'

```
Does somebody know why it works for the full version but not for the tiny version?
Any help is very much appreciated.

**Comment by TNTWEN** [comment]
Hello！@4444borja 
I think your OpenVINO version is lower than 2020R4

**Comment by 4444borja** [comment]
@TNTWEN Thank you for your quick response!
I checked my version, i have installed openvino_2020.4.287 which should be enough.
I ran the setupvars.sh script of that version so it should be using 2020R4.

Any idea if this could be because of something else?

**Comment by TNTWEN** [comment]
@4444borja 
You have install two version of OpenVINO on your PC? Do you make sure everything is right?
I have met this error before,but it was solved when i installed  openvino_2020.4.287.
And this repos ‘s yolov4-tiny have been tested on python and C++ demo

**Comment by 4444borja** [comment]
@TNTWEN 
Okay, it must be a problem with my installation then. I will check!

**Comment by 4444borja** [comment]
Hi @TNTWEN ,
I checked several times in different machines, and the problem still exists, but only on the yolov4-tiny model.

The yolov4 full model works good, and I am able to run the demo with the camera on real time, but when I try the same thing with the tiny model, it gives the error below

> Traceback (most recent call last):
>   File "object_detection_demo_yolov3_async.py", line 518, in <module>
>     sys.exit(main() or 0)
>   File "object_detection_demo_yolov3_async.py", line 398, in main
>     args.keep_aspect_ratio)
>   File "object_detection_demo_yolov3_async.py", line 233, in get_objects
>     out_blob = out_blob.buffer.reshape(net.layers[net.layers[layer_name].parents[0]].out_data[0].shape)
> KeyError: 'detector/yolo-v4-tiny/strided_slice/Split.0'

Any idea? 
Thank you in advance!

**Comment by 4444borja** [comment]
@TNTWEN 
Hello!
The problem, as you said, was because I was using an earlier OpenVino installation than the one required (2020R4).
The problem persisted because, after updating OpenVino, I was testing on a model converted with the earlier version instead of reconverting it to OpenVino with 2020R4.
Apologies for the mistake and thank you
